### ISSUE TITLE
Dataset Abstractions

### ISSUE THREAD

**Issue by tbreloff** [Evizero/LearnBase.jl#14]
I'm not sure if this belongs here, or maybe MLDataUtils.jl?  I want to develop an abstraction surrounding datasets, likely similar to: https://github.com/tbreloff/OnlineAI.jl/blob/dev/src/nnet/data.jl#L136

The concept is that there are many types of data sets, and many ways to access that data.  It would be nice if the models/solvers did not need to know about any of this, and we could reduce much of the interface to simple iteration.

Desired API:

```julia
# given input/target data in some format, get n random samples from the dataset
for (input, target) in RandomSampler(data, n)
    output = fit!(model, input, target)
    # do something with output?
end

# k-fold cross validation.. partition the dataset (without data copies!)
for (train, validate) in CrossValidation(data, k)

    for (input, target) in RandomSampler(train, n)
        # fit, etc
    end

    # access each pair once, sequentially
    for (input, target) in DataIterator(validate)
        # do something with the validation set
    end
end
```

I think you can get the idea.  This would be a nice pattern to have available, partly because it could handle many different types of incoming data, and partly because it cleanly separates data from algorithms.

Thoughts?

**Comment by Evizero** [comment]
I agree with you. I had similar thoughts before at https://github.com/Evizero/SupervisedLearning.jl but I got sidetracked with backend stuff like KSVM. Also, I like your proposal better.

That said we should not tackle all at once. Ideally I would like https://github.com/Evizero/LearnBase.jl/pull/10 to get merged and then go on from there. I'm working on an image augmentation package for my PhD and I would like to embrace LearnBase there where it makes sense (for example the `transform` verb). So a somewhat stable state would be nice

**Comment by tbreloff** [comment]
I think I'd be happy to merge the PR as-is, whenever you're ready. 

As for datasets... Should I make a PR here or MLDataUtils?

**Comment by Evizero** [comment]
Ok I'll review the code then soon.

> Should I make a PR here or MLDataUtils?

Sure, we can approach PRs there as we did here, which I think worked pretty well

**Comment by tbreloff** [comment]
Ok I'll try to add to MLDataUtils... again it will probably follow closely to what I built for OnlineAI, but diverge when needed.

Here's a rough list of "data access patterns"... let me know if you think of any others:

- [ ] Sequential, ordered (time series, etc)
- [ ] Shuffled (once per data point, but random order)
- [ ] Partitioned (create multiple iterators, one per data partition)
- [ ] Random, Infinite (just keep sampling)
- [ ] Stratified sampling (sample equally from each target class)
- [ ] Cross validation (create k partitioned iterators for cross validation)

And some forms that the data might arrive:

- [ ] `RowMatrix`: we should make this class to allow cache efficient row-based access
- [ ] Matrix: columns are data points
- [ ] Vector of Vectors
- [ ] Vector (equivalent to nx1 matrix)
- [ ] Vector of `(input,target)` tuples

**Comment by Evizero** [comment]
I like everything in your last post. Never occured to me to put CV iterators in MLDataUtils, but I like it. My original intend was mainly for artificial data set generators. Now that you put the idea into my head I can't think of a better place. Looking forward to reviewing your PR
