### ISSUE TITLE
ready for prime time?

### ISSUE THREAD

**Issue by tbreloff** [Evizero/LearnBase.jl#8]
@Evizero I'm working on a new recurrent neural net framework within OnlineAI, and I'm considering whether I can switch the loss models to those in LearnBase.  I see you haven't pushed any updates in a while... what is your latest thinking on this repo?  There are a few minor aspects that I would consider changing (remove UnicodePlots dependency, add "Abstract" to some of the type names, etc), as well as some conventions (multiplying by 0.5 for L2 loss, for example)... but I expect most of this is good as-is.  What's your opinion on the current state of the package, and would you be happy for me to submit PRs to change some of this stuff to my liking?

**Comment by Evizero** [comment]
Hey Tom!

Yes, my Github activity took a huge hit the past few months for work related reasons, but I still believe in the goals of this package. Another thing that made me back up a little is that I got obsessed with thinking of how to make this package general enough to allow for GPU implementations, but I have yet to find a good solution (I am prone to over-engineering, which can be paralysing at times).

There are some things I did that I am not completely happy with, which is essentially the content of the risk folder https://github.com/Evizero/LearnBase.jl/tree/master/src/risk . Predictor is basically the equivalent to an activation function in neural networks, and I would like for a `EmpiricalRisk` to be able to dispatch on both `Predictor` and `Loss` to have custom implementations for the cases where the math for the chain rule simplifies. For example a sigmoid activation function with a crossentropy loss results in the very simple gradient `t - y`. Anyhow that was the idea, but I am still not sure it's the best approach. Maybe I am over-engineering it again.

I was also experimenting with how I could make use of a general purpose optimization package like Optim in an efficient way without closures, but that the `optim` folder is more or less throw away code.

What I am very happy with are the loss functions. They are also well tested I think. It is also close to the most elaborate theory about loss functions that I came across. I also discussed this with a colleague who focuses on "modern" stochastic optimization and we will likely cooperate on something that actually needs to make use of a lot of properties like convexity, and lipshitz-cont, etc, of loss functions and penalizers. But this might be months in the future.

The L2 loss is implemented this way for consistency with the more general LP loss, but I do see the appeal performance-wise and am open to the idea. Maybe create a `FastL2Loss`?

Concerning UnicodePlots: A big goal of that package was to be used to create good custom `show` methods, which I really like for the loss functions in this case. It is very lightweight and I would like to leave it in if you are not too opposed to it. At least during the development of this package I would like to experiment with what kind of visualizations are useful vs annoying etc.

All in all I would be very happy if you were giving it a shot from your neural network use case. I have already re-factored KSVM to use LearnBase, and I think it improved this package quite a lot. But I recognize that there is still a long way to go and am willing to refactor according to changes here.

Since I wouldn't the only "user" of this package anymore, we should then switch to PR-based changes as you proposed. You should be able to push branches to this repo directly, so there is no reason to fork.

I am looking forward to your input.

**Comment by tbreloff** [comment]
> I would like for a EmpiricalRisk to be able to dispatch on both Predictor and Loss to have custom implementations for the cases where the math for the chain rule simplifies. For example a sigmoid activation function with a crossentropy loss results in the very simple gradient t - y.

We're on the same page here.  I have a pretty hacky method to achieve this in OnlineAI, which is that I return the simplified calc with a boolean that says whether or not to multiply by the "predictor derivative".  It works, but it has been bugging me for a while.  I'd like to come up with a cleaner solution.

> Concerning UnicodePlots: A big goal of that package was to be used to create good custom show methods

I get that... would you be open to using the Requires package for conditional inclusion?  Then when you do a `using UnicodePlots` the show method would be overwritten.

**Comment by Evizero** [comment]
> I get that... would you be open to using the Requires package for conditional inclusion?

Sure, if it bugs you this much.

**Comment by Evizero** [comment]
Although I think an if statement checking if unicodeplots is in scope would be even simpler. I've seen other code use UnicodePlots that way

**Comment by tbreloff** [comment]
Expanding a little... there are several stages of abstraction that I care about:

- cost/loss model
- activations
- penalty functions
- gradient computations

You could say that `totalCost = w * predictionCost + (1-w) * penaltyCost` for some w in [0,1].  The gradient computation is dependent on all 3 of the categories, as it is a function of {predictionCost, penaltyCost, derivativeOfActivation} for all timesteps.  So I suppose the ideal solution is to allow the gradient calculation to "see" the other abstractions and have it call the value/derivative functions directly.

In OnlineAI, I have the abstractions `GradientModel` and `GradientState` which take the `predictionCost * activationDerivative` value during parameter update and apply a fixed `penaltyCost`, updating the `GradientState` in the process.  See the [Adam model](https://github.com/tbreloff/OnlineAI.jl/blob/dev/src/nnet/gradient.jl#L113-L141) for example.

I don't like this, and I'd prefer a flow which isn't so tied together.

**Comment by Evizero** [comment]
I am not sure I know what you mean. Are you talking about computing the "total gradient" ? Since it's addition I compute them separately (using dispatch) and add them up. See https://github.com/Evizero/LearnBase.jl/blob/master/src/risk/empiricalrisk.jl#L83-L98 for example. You can also see in the file that there are different methods for different combinations

**Comment by Evizero** [comment]
As a sidenote the selected code from the last post is the most general (and slowest) implementation for when there is nothing special known about about the parameters. If one knows that the predictor is linear then there is more efficient code further down https://github.com/Evizero/LearnBase.jl/blob/master/src/risk/empiricalrisk.jl#L122-L158

**Comment by tbreloff** [comment]
> Are you talking about computing the "total gradient" ?

Yes essentially.  Although the `GradientModel` I refer to is an abstraction above the individual gradients.  It is a model for collecting individual gradients through learning and applying a weight change based on some update rule.  Some examples of gradient models: SGD, SGD with momentum, AdaGrad, RMSProp, Adam, etc.  All of these take the "total gradient" as input each timestep, update an internal model state, and return the parameter adjustment to apply.   Ideally this abstraction doesn't need to know about how the total gradient is computed, and additionally it shouldn't care whether it's computing the update for a weight matrix or a bias vector.

I'm not convinced that this fits directly into the term "Empirical Risk Minimization", of course I've always hated that term for unfounded reasons.  I'd prefer that an improved version of GradientModel/GradientState could be moved into LearnBase, as I'd also like to see these available for OnlineStats.  cc: @joshday

Lets bikeshed on names for a bit:

- Cost --> PredictionCost
- Penalty --> ParameterCost
- Predictor --> TransferFunction  (see [this](https://en.wikipedia.org/wiki/Artificial_neuron) for justification of that name)
- Optimizer --> ParameterUpdateModel  (equivalent to my GradientModel)

I feel like these are a little more descriptive, and maybe less likely to invoke confusion between researchers (which is a barrier to getting people to use this package).

**Comment by Evizero** [comment]
Does the optimizer really have to be weaved into the computation of the value / gradient? It seems to make more sense to be build on top of it.

I can do that just fine with Pegasos for example, which is stochastic: see https://github.com/Evizero/KSVM.jl/blob/master/src/linear/solver/pegasos.jl

**Comment by Evizero** [comment]
I think you might be on to something with the names. However, I would refactor `Pedictor` to `PredictionFunction` then to be consistent with `PredictionCost`

**Comment by tbreloff** [comment]
> Does the optimizer really have to be weaved into the computation of the value / gradient? It seems to make more sense to be build on top of it.

Correct... this is what I'm saying.  [Pegasos](https://github.com/Evizero/KSVM.jl/blob/master/src/linear/solver/pegasos.jl#L114) is a good example of something that would better fit as a concrete subtype of `ParameterUpdateModel`.  It updates it's state (which only needs to track the number of updates, if I read that correctly), then returns the calculated parameter change (i.e. `Δw[i,j]`)

Then the "Pegasos solver" would be just a generic solver using the `PegasosUpdateModel`.

>  I would refactor Pedictor to PredictionFunction then to be consistent with PredictionCost

That makes sense.

**Comment by Evizero** [comment]
Ok, I think I am slowly getting the picture. To check this, do we both agree that the `ParameterUpdateModel` does not belong into [that data structure](https://github.com/Evizero/LearnBase.jl/blob/master/src/risk/empiricalrisk.jl#L4-L8), but uses it instead?

Which raises another question, should we rename `EmpiricalRisk` as well?

**Comment by Evizero** [comment]
Theory wise, a lot of people would actually say that what I called `EmpiricalRisk` is actually a `StructuralRisk` because a penalty is involved, so I am ok with changing the name to be more descriptive (if only to avoid that criticism)

**Comment by tbreloff** [comment]
>  do we both agree that the ParameterUpdateModel does not belong into that data structure, but uses it instead?

Agreed.

> so I am ok with changing the name to be more descriptive 

Cool.  I really don't know what to call it, and part of me wishes it doesn't exist at all.  I'll give an example why:

Say I have a basic feed forward neural net with 2 hidden layers.  The first layer applies a ReLU activation (PredictionFunction), the second a sigmoid.  However, I want to use the same penalty (ParameterCost) and cost (PredictionCost) functions.  (Actually now that I think about it, the first layer doesn't need the PredictionCost... only output layers would need it.)  It feels strange to require two "EmpiricalRisk" objects, each wrapping the same cost types.  I feel like it would be nicer to just pass all component models into methods directly.

That said... I see the advantage of packaging the models into a wrapper, so you don't have to pass them all around constantly.  Could it be called `ParameterModels` or something similar?

**Comment by tbreloff** [comment]
Maybe instead of `ParameterUpdateModel` it could be `ParameterUpdater`.  We could also replace `Parameter` prefixes with any of:

- Param
- Coef
- Coefficient

**Comment by Evizero** [comment]
The point you raise is very valid. I am also unsure how to make incorporate backprob into this. However, it covers the whole domain of empirical- and structural risk minimization, which is quite useful. 

Maybe we can find a way to only use this for the outputlayer and have some other structure for hidden layers?

**Comment by tbreloff** [comment]
> Maybe we can find a way to only use this for the outputlayer and have some other structure for hidden layers?

It's ok (IMO) to assign a PredictionCost model to a hidden layer which never gets used.  Then I don't need to treat layers differently (except in the update method of the enclosing network).  But it gets back to the point that the `EmpiricalRisk` object shouldn't be much more than a simple replacement for a Tuple of models.

**Comment by tbreloff** [comment]
@Evizero: Is there a reason you have submodules (LossFunctions, Penalties)?  Seems like unnecessary hassle unless you were planning on conditionally including somehow (which I don't think is very easy to do).

**Comment by Evizero** [comment]
the reason is a convenient autocompletion for the user. I. e. the user can easily see what lossfunctions are available. i'm open to changing that

**Comment by tbreloff** [comment]
That's a good reason I never considered.  If we can't think of a better solution to that then I'm ok keeping as-is.

**Comment by tbreloff** [comment]
Also... where do you stand in the "Cost" vs "Loss" debate?  It feels strange to have `Loss <: Cost`... can they all be subtypes of `PredictionCost`?

**Comment by tbreloff** [comment]
And is there really a need for the split of Supervized/Unsupervized loss?  Do you have an example in mind where that would be necessary?

The way I see it, it should be ok to say:

```
abstract PredictionCost
abstract MarginBasedCost <: PredictionCost
abstract DistanceBasedCost <: PredictionCost
```

**Comment by Evizero** [comment]
Concerning `Cost` vs `Loss`, at this point I am ok with renaming `Loss` to `PredictionCost` and removing `Cost`

Concerning supervised / unsupervised. Aside from being part of the theory I think it makes practical sense as well, The supervised loss is a function of `target` and `f(data)`, while the unsupervised one is a function of  `data` and `f(data)`. So they should be distinct. One such unsupervised loss would be a reconstruction error for example

**Comment by Evizero** [comment]
Come to think of it, maybe `PredictionLoss` instead of cost etc? `L2Cost` or `HingeCost` sound very strange

**Comment by tbreloff** [comment]
> The supervised loss is a function of target and f(data), while the unsupervised one is a function of data and f(data). So they should be distinct. One such unsupervised loss would be a reconstruction error for example

For reconstruction error, that is supervised loss with `target = data`.  The examples I can think of that qualify as "unsupervised" still can be framed as "supervised by a function of the input data", and that mapping should probably happen outside of the "loss model".

> PredictionLoss instead of cost etc?

I'm ok with this if you feel strongly.

**Comment by Evizero** [comment]
Let's use Loss instead of Cost then to not make the lossfunctions sound weird (crossentropycost !?). 

I am ok with removing Supervised and Unsupervised for now and reopen the discussion for a reintroduction when an actual use-cases arises

**Comment by tbreloff** [comment]
Going back to the discussion of submodules... I find it really annoying that after `using LearnBase`, the concrete loss functions are not exported (only the `LossFunctions` name and the abstract types are exported).  This, and general simplification of the code, seem to outweigh the tab-completion argument (IMO).

**Comment by Evizero** [comment]
I'm ok with dropping the Submodules. Basically I wanted to give it a try.

**Comment by tbreloff** [comment]
Cool... I'm working on a PR now.  I'll push it up with the submodules still in, and we can discuss further there.

**Comment by Evizero** [comment]
I also suspect that the tab completion could also be achieved by having a separate file with an empty `LossFunctions` submodule that simply import and exports all the loss functions. But I never got around to try that

**Comment by Evizero** [comment]
How about changing Param to Coefficient? What's your opinion on that?

**Comment by tbreloff** [comment]
I could get behind Coefficient vs Parameter, but I don't love the length of it.  Do you like `Coef`?

**Comment by Evizero** [comment]
`PredictionLoss` is long too, but since it's an abstract type I actually prefer it over `PredLoss`.
I think `ParameterLoss` sounds pretty good and consistent

**Comment by tbreloff** [comment]
Ok... `ParameterLoss` works for me.

**Comment by Evizero** [comment]
Snooping around in your OnlineAI code I came across the `@enum` macro [here](https://github.com/tbreloff/OnlineAI.jl/blob/master/src/nnet/solver.jl#L38). Can those be used to dispatch on? If so I might actually prefer them for specifying if a predictor function uses an intercept (see [here](https://github.com/Evizero/LearnBase.jl/blob/master/src/risk/prediction.jl#L1)). Currently I am forcing the unrestricted type parameter to be either `true` or `false` for what would probably be clearer as either `BIAS` or `NOBIAS`

**Comment by tbreloff** [comment]
With regards to the Predictor type: I was wondering if combining an affine transformation with activation/squashing function should be two separate steps.  Specifically, my purposes allow for an activation function to act on the "state s", and that state may not directly coincide with `wx+b`.  Put another way, I want to perform actions on `f(s)`, knowing only `f` and `s`, and not knowing/caring that `s = wx + b`.

So with that in mind... is `ActivationFunction` a good term for this?  Can we then also define an `AffineTransformation`, which would be similar in concept to your `LinearPredictor`?  For my purposes, I would probably only use the activation function... I would accomplish the affine transformation internally within OnlineAI.

Another thing to keep in mind is that many "predictor/activation functions" will first apply an affine transformation before some other function (sigmoid, tanh, softsign, relu, prelu...), so I think it makes sense to abstract that part away.

**Comment by Evizero** [comment]
I know what you mean. Basically this is what I am doing with the sigmoid predictor here https://github.com/Evizero/LearnBase.jl/blob/master/src/risk/prediction.jl#L124-L138, but I keep the information about the intercept around to avoid boxing.

But there is also another way to think about it outside of neural networks. When you look at the typical notation for linear regression, for example from the ML class in Stanford, then the prediction model (to which they also refer as hypothesis), denoted as `h`, can be the simple linear, affine, or sigmoid prediction function. i.e. they are all on the same conceptual level.

That being said, I am ok with moving away from this if it doesn't make things like linear regression, margin based logistic regression, and sigmoid based logistic regression more complicated. In a way I still would like the code to serve as a reference implementation for newcomers.

What about the following (I didn't test this, I am coding on the fly on github):

```julia
abstract AbstractTransformation
abstract AbstractActivation

immutable PredictionFunction{T <: AbstractTransformation, A <: AbstractActivation}
    transform::T
    activation::A
end

# some examples
immutable AffineTransformation{INTERCEPT} <: AbstractTransformation
    bias::Float64
end
immutable IdentityActivation <: AbstractActivation end
```

And then linear regression would be defined:

```julia
typealias AffinePredictionFunction{INTERCEPT} PredictionFunction{AffineTransformation{INTERCEPT}, IdentityActivation}

# convenience constructor
function AffinePredictionFunction(bias::Real) 
   ...
end
```

I think one could `@inline` the functions for the `IdentityActivation`, which should result in no performance overhead for those that don't need activation functions

**Comment by tbreloff** [comment]
I'm a little unsure what is best here. Part of the problem is that I can't think of a scenario where you want a type for adding a constant bias. 

I think Transformation is the right abstraction, and that an activation function is just a type of transformation. So maybe I'll just copy the types from https://github.com/tbreloff/OnlineAI.jl/blob/dev/src/nnet/activations.jl and make ActivationFunction <: Transformation. Then we can add an AffineTransformation <: Transformation later if needed?

**Comment by Evizero** [comment]
> Part of the problem is that I can't think of a scenario where you want a type for adding a constant bias.

For some applications, such as support vector machines it is more useful to treat the bias separately. There are algorithm where the optimization problem or convergence actually changes depending on if an intercept is present and how the intercept is treated (penalised or not). Now, in the case that no bias is present then the code can simplify quite a bit, which also improves performance.

> .. make ActivationFunction <: Transformation. Then we can add an AffineTransformation <: Transformation later if needed?

I'm a bit reserved. I like the idea of the activation function not having to worry how the real number was computed. Also, I am thinking about a sigmoid logistic regression, which would need a sigmoid activation. In your example how is the bias specified? Does it suddenly need to be augmented into the dataset, while for margin-based it is separate?

What do you think about the little code snipped I posted before

```julia
immutable PredictionFunction{T <: AbstractTransformation, A <: AbstractActivation}
    transform::T
    activation::A
end
...
```

Does this approach align with your needs / views in any way?

**Comment by tbreloff** [comment]
Thinking about abstractions.... what is a logistic regression?  It takes an input vector (x), multiplies a parameter matrix (w), adds a bias vector (b), and applies the sigmoid function (f).  We then compare `f(wx+b)` to the target and algorithmically adjust w and b to best fit the relation.  Logistic regression is actually a special case of a classic ANN: it has 1 output neuron with a sigmoid activation, and no hidden layer.  Much of machine learning can be similarly generalized to be a directed graph of transformations, where some part of the graph can be learned to improve the output.

I think the case can be made that each of these are "transformations":
- `w*x` is a linear transformation
- `z+b` is a translation
- `w*x + b` is an affine transformation
- `f(s)` is a ??? transformation (depends on function)

For my purposes, the important distinction between f(s) and the others is that f(s) is a transformation which **does not have parameters to be fit**.  It is a deterministic mapping from input to output, and so it can get special treatment in the pipeline.

With that said, I think it would be useful to discuss the idea of having a "mapping/activation transformation" differentiated from a "learnable transformation"  (please bikeshed the names).  The important distinction being that one is a fixed mapping, and one has parameters that should be changed/improved during fitting.  How about:

```
Transformation
    ActivationFunction
        Identity
        Sigmoid
        Tanh
        ...
    Learnable
        Translation
        LinearTransformation
        AffineTransformation
        ...
```

And something like logistic regression would be defined by a series of transformations, some of which could be fit/learned:  input --> affine --> sigmoid --> error function

@joshday I'm really curious regarding your thoughts on how this might fit in with your design decisions in OnlineStats.  It is a concept that I continually come back to... that most models/functions are just mappings from input to output, and that our goal should be generic pipelines from data through models and into various output formats (business actions, reports, plots, etc).  Also that we should be able to define the pipeline in a plug-and-play approach and new streaming data is automatically "piped through", updating model fits and producing outputs.

I care most about the activation functions because I'm not ready to commit to a fully generic "learnable transformation" approach... but I think that's the most powerful/elegant abstraction for the long term.

**Comment by Evizero** [comment]
I agree that most linear regression variants can be viewed as a single neuron, but that connection stops being useful as soon as kernels are involved.

Hmm, the amount of constraints makes it hard for me to see the benefit of such an abstraction. For example affine -> affine isn't really defined (is it?), and input -> sigmoid, while possible, doesn't make too much sense. It seems clear that what happens is usually input -> reduction -> activation

**Comment by tbreloff** [comment]
Kernels are like activation functions, in that they are a deterministic mappings from input to output, and an SVM is effectively input--> kernel --> affine --> error function (i think! You know SVMs better than me though). 

So yes, most regressions are input --> kernel --> learnable --> activation --> error, and basic feedforward ANNs are like stacked regressions, where only the last layer feeds to an error function. However that's missing the power of the abstraction. What if I could (very easily) inject a SVM in a directed graph of transformations? Then I could regress both on the features of a neural net and a decision of a SVM. 

Yes you could pull that off without the abstraction, but it would require a lot of boilerplate/glue code. 

That said... I only really care about activation functions in the short term, so the rest of the  abstraction can wait.

**Comment by Evizero** [comment]
I'm sure there is *some* way to squeez kernels into that thinking, but I'm not sure it will be a useful representation. I still believe that someone reading an SVM algorithm implementation should be able to follow what is going on (otherwise why not use a c-library binding), so I am somewhat reserved to abstract to much. That being said, I think I see your point and what you are aiming at, which I also think would be nice.

Well how about this. Let's go only so far with the abstraction as we need **right now** (to avoid the over-engineering).

I think:

```julia
immutable PredictionFunction{T <: AbstractTransformation, A <: AbstractActivation}
    transform::T
    activation::A
end
```

while not the perfect abstraction, covers both our use cases for now? (We can call the `AbstractTransformation` something like `AbstractReduction` to avoid confusion later on.)

We could then after some point refactor when we see how and where this fails us. I'd like to make somewhat incremental progress, so that my brain can keep up with what is useful and what isn't.

what do you think? do you have a different suggestion as a digestible first step?

**Comment by tbreloff** [comment]
Github butchered my email response before, so I don't think you saw the whole response.  Here it is again:

> Kernels are like activation functions, in that they are a deterministic mappings from input to output, and an SVM is effectively `input --> kernel --> affine --> error function` (i think! You know SVMs better than me though).

> So yes, most regressions are `input --> kernel --> learnable --> activation --> error`, and basic feedforward ANNs are like stacked regressions, where only the last layer feeds to an error function. However that's missing the power of the abstraction. What if I could (very easily) inject a SVM in a directed graph of transformations? Then I could regress both on the features of a neural net and a decision of a SVM. 

> Yes you could pull that off without the abstraction, but it would require a lot of boilerplate/glue code.

> That said... I only really care about activation functions in the short term, so the rest of the  abstraction can wait.

In the short term, the path forward is probably to just do activation functions, which are subtypes of `Activation <: Transformation`.  Then we can expand the meaning of a transformation later.  I won't use your `PredictionFunction` type in the short term, as the "reduction" will be handled elsewhere... so even that is unnecessary for me.

In the long term, I think we should pick a few models (ANN, SVM, Random Forest?) and see what similarities arise in an implementation.  Then maybe the best abstraction will be obvious.

**Comment by Evizero** [comment]
I did see the full message (I got suspicious for some reason and opened the folded history)

Ok, let's try that then. maybe something will develop naturally

**Comment by joshday** [comment]
This stuff has potential to work well with OnlineStats.  I'll wait a bit to see what this next iteration of LearnBase looks like and then try reimplementing `StatLearn` with it to check for performance regressions.
